name: ChatGPT Workflow

on:
  push:
    branches:
      - main

jobs:
  chatgpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install openai  # Install the openai library

      - name: Run ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          import os
          import openai

          # Set your OpenAI API key from the GitHub secret
          api_key = os.environ['OPENAI_API_KEY']

          # Define the message you want to send to ChatGPT
          message = "What is the weather like today?"

          # Make a request to the ChatGPT API
          response = openai.Completion.create(
              engine=gpt-3.5-turbo,
              prompt=message,
              max_tokens=50,
              api_key=api_key
          )

          # Extract the response text
          chatgpt_response = response.choices[0].text

          # Print the response
          print(chatgpt_response)